#include "buttons.h"

void button_init(void){
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER &= ~(GPIO_MODER_MODER2 | GPIO_MODER_MODER3 | GPIO_MODER_MODER1 | GPIO_MODER_MODER0);
	GPIOA->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR2 | GPIO_OSPEEDER_OSPEEDR0 | GPIO_OSPEEDER_OSPEEDR1 | GPIO_OSPEEDER_OSPEEDR3);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR2 | GPIO_PUPDR_PUPDR0 | GPIO_PUPDR_PUPDR1 | GPIO_PUPDR_PUPDR3);
	//now to enable interrupt on it
	SYSCFG->EXTICR[1] &= ~(0xFFFF);
	EXTI->FTSR |= (EXTI_FTSR_TR2 | EXTI_FTSR_TR3 | EXTI_FTSR_TR1 | EXTI_FTSR_TR0);
	EXTI->IMR |= (EXTI_IMR_MR2 | EXTI_IMR_MR3 | EXTI_IMR_MR0 | EXTI_IMR_MR1);
	//set the priority
	NVIC_SetPriority(EXTI2_3_IRQn,1);
	NVIC_EnableIRQ(EXTI2_3_IRQn);

	NVIC_SetPriority(EXTI0_1_IRQn,1);
	NVIC_EnableIRQ(EXTI0_1_IRQn);
}

